### ISSUE TITLE
Appreciations for the amazing work and a document request

### ISSUE THREAD

**Issue by earthjeffone** [emrahcom/emrah-buster-templates#1]
Hi,
My name is Jeff, and I want to thank you for sharing this work. It is really important in these times to be able to communicate :) I am working on a small project to help my friend play his music live on the various sites. I am wondering if you would be willing to add a walkthrough for the process of connecting the eb-jicobi with the eb-livestream. I imagine it's pretty simple I am just having trouble figuring out where to look.

I'd be happy to help update the docs  if that would be of service... I noticed a couple of things that would be helpful to include!

Your website is really neat.  That is so amazing what you can do with the robots.

Take Care and I hope you and your family are well!

Jeff

**Comment by emrahcom** [comment]
Hi Jeff,

I didn't know what is **eb-jicobi**. Did you mean **eb-jitsi** or something else? If there is something called **eb-jicobi**, could you send me a link about it?

emrah

**Comment by earthjeffone** [comment]
Hi Emrah, 

Thanks for the reply. I typed that late at night and had brain fog after being at a computer for too long. I  had never worked with containers before so I am learning. and figured out.  I mistyped jicobi, and meant to type Jibri. I had to start the eb-jibri-template before I could attach to it..

I am trying to connect Jibri , to the live streaming server to push to fb and others ect....

How do I correctly modify:
 
/usr/local/bin/ffmpeg   

To send the stream to FB, I imagine I input the stream key somewhere in this line:

> DST=$(echo $DST | sed 's~rtmps://live-api-s.facebook.com:443/~rtmp://127.0.0.1:1936/~')

I also am wondering if I am correct that, to connect to the eb-livestream instance, I would input here?

    ARGS=$(echo $ARGS | sed "s~rtmp://nameof.server/*~~")

Are there any other steps I am missing?

I've gained some insights going through the install process a few times. May I do some work on the documentation and submit a pull request?

Thanks for the beautiful code. I was struggling trying to get it to work otherwise.

Take Care,

Jeff

**Comment by emrahcom** [comment]
Hi Jeff,

If you installed **Jibri** using the **eb-jibri** template or the **eb-jitsi** template, you don't need to do anything else to push to Facebook or to a custom RTMP server. Just use the destination RTMP address as the stream key on the Jitsi user interface. All customizations were already done and it's ready to push to Facebook.

You don't need the eb-livestream server too if you have only one destination (push) address at a time.
