### ISSUE TITLE
Jibri recordings cannot be accessable

### ISSUE THREAD

**Issue by hakdag** [emrahcom/emrah-buster-templates#2]
I have installed a JMS node using the template you provided.

https://github.com/emrahcom/emrah-buster-templates/blob/master/doc/jitsi_cluster.md

I have just installed JMS nothing else. Jitsi is working and I could record.

But when finish recording, I didn't receive any file download or anywhere to download the recorded file. I checked the recordings folder and saw the following output:
![image](https://user-images.githubusercontent.com/5295212/88642885-b3193900-d0c9-11ea-8555-e0ac579d514f.png)

I recorded 3 recordings. I think they don't look normal. What is missing here?

Thanks for helping.

**Comment by emrahcom** [comment]
The recorded MP4 files are under these folders. These are the randomly named folder names. To list their contetnts

ls -alh /usr/local/eb/recordings/*

There are an MP4 file and a metadata.json file in each folder.

**Comment by hakdag** [comment]
Thank you very much for answering. I can see the recorded MP4 files under these folders. Is it possible to download them via the Jitsi meet interface after the recording is finished? Is there such a feature?

**Comment by emrahcom** [comment]
You can add an Nginx location to download it through a web browser.

Attach to the eb-jitsi container
`lxc-attach -n eb-jitsi`

Create a secret link to point the recording folder
`ln -s recordings /usr/local/eb/my-secret-place`

Add a new location to the Nginx config `/etc/nginx/sites-enabled/YOUR-HOST-ADDRESS.conf`
After the `gzip_vary on` line
```
gzip on;
gzip_types text/plain text/css application/javascript application/json;                                                            
gzip_vary on;

location ^~ /my-secret-place {
    root /usr/local/eb;
    autoindex on;
}
```

And reload the nginx
`systemctl reload nginx`

Through the web browser https://YOUR-HOST-ADDRESS/my-secret-place


Another way is to customize the finalize script (`/usr/local/bin/finalize_recording.sh` in the Jibri container)

**Comment by hakdag** [comment]
Thank you, I will do it.
