### ISSUE TITLE
Error while adding additional Jitsi Videobridge node

### ISSUE THREAD

**Issue by hakdag** [emrahcom/emrah-buster-templates#3]
Following the guide steps provided here:

https://github.com/emrahcom/emrah-buster-templates/blob/master/doc/jitsi_cluster.md#3-additional-jitsi-videobridge-jvb-node

Using digital ocean's Debian 10 droplet. I installed JMS described as in the preceding steps in the guide. Currently at the following step:

wget -O - https://meet.mydomain.com/static/jms.pub >> /root/.ssh/authorized_keys

I received the following error:

Resolving meet.mydomain.com (meet.mydomain.com)... <IP_Address>
Connecting to meet.mydomain.com (meet.mydomain.com)|<IP_Address>|:443... connected.
ERROR: The certificate of ‘meet.mydomain.com’ is not trusted.
ERROR: The certificate of ‘meet.mydomain.com’ doesn't have a known issuer.

I have replaced the original domain with 'meet.mydomain.com' and IP address.

**Comment by emrahcom** [comment]
Could you use the following command for a quick fix.
```
curl https://meet.mydomain.com/static/jms.pub >> /root/.ssh/authorized_keys
```

I will check it. Thanks for the feedback

**Comment by hakdag** [comment]
Thank you very much. curl worked.
