### ISSUE TITLE
eb-jibri and finalize_script.sh

### ISSUE THREAD

**Issue by johnxyasay** [emrahcom/emrah-buster-templates#5]
Hi Emrah thank you for making this buster-templates for us, really big help!

There's just this one thing I want to ask. I'm doing finalize_script for post recording on jibri with rclone to auto upload it to my cloud drive. Is there a way to run the finalize_script on my root host user from the jibri container? Sorry I'm quite a newbie when it comes to lxc

**Comment by emrahcom** [comment]
Why do you want to run it on host?

**Comment by johnxyasay** [comment]
Hi @emrahcom thank you for you response, I just want to run it on my host so it will have a a base script for my finalize script and not installing rclone on every jibri container.

**Comment by emrahcom** [comment]
It's possible to run it on the host but this way is more difficult than installing rclone to Jibri.

All jibri instances are created from the `eb-jibri-template` container. Therefore if you install rclone to template, it will be available for all instances too.

Steps:

- stop jibri containers
```bash
systemctl stop jibri-ephemeral-container.service
```

- start the template as a container
```bash
lxc-start -n eb-jibri-template
```

- attach the running template
```bash
lxc-attach -n eb-jibri-template
```

- install the needed packages and configure them
```bash
apt-get update
apt-get install rclone

cd /usr/local/bin
ls
vim finalize_recording.sh
...
...
```

- stop the template (be carefull, dont stop the host)
```bash
poweroff
```

- start the jibri instances again
```bash
systemctl start jibri-ephemeral-container.service
```

**Comment by johnxyasay** [comment]
Ohh I see, this is very convenient @emrahcom didn't know that I can do that, will do this! Thank you for your amazing work! :)

**Comment by johnxyasay** [comment]
Last question @emrahcom, is there a way to have multiple jibri instances on my server given I have 32 cores/ 64 gb instance? or do we really need to host it on another instance? I'm just quite confused on adding new jibri nodes as to add it on the same instance as the JMS

**Comment by emrahcom** [comment]
Both are possible. For the first option, all you need to do, stop the server, increase the number of cores (if this is a VM) and restart it.

After the base 4 cores, one jibri instance will be started for each additional 4 cores. For example if you have a 32 cores, after the reserved the first 4 cores for the base processes, 7 jibri instances will be started.

32 - 4 = 28 cores for the Jibris
28 / 4 = 7 instances ( 4 cores for each one)

**Comment by johnxyasay** [comment]
oh I see you have it automated based on cpu number, I gotta change my quota limit first for gcp. Just curious where do you calculate the cpu availability?

Thank you for the prompt response, you really helped me a lot with your repo <3

**Comment by emrahcom** [comment]
> Just curious where do you calculate the cpu availability?

According to my experiences but all cores are not the same. If this doesn't suit for you, you can configure it from `/usr/local/sbin/jibri-ephemeral-start`

[jibri-ephemeral-start](https://github.com/emrahcom/emrah-buster-templates/blob/master/machines/eb-jitsi-host/usr/local/sbin/jibri-ephemeral-start)

**Comment by johnxyasay** [comment]
Thank you emrah, closing this now :)
