### ISSUE TITLE
eb-buster doesn't exist

### ISSUE THREAD

**Issue by Guiraud** [emrahcom/emrah-buster-templates#6]
Hi thanks for this marvellous script. Althought, I came accross a little problem that might find its source in my lack of knowledge.

On my cloud debian ( Scaleway ), I changed the default kernel : 
`
user@host:~$ uname -a
Linux almost.theater 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux
`
and when i run the scrip to install Jitsi/jibri, i get  : 
`
-------------------------- eb-buster --------------------------
eb-buster doesn't exist
lxc-stop: eb-buster: tools/lxc_stop.c: main: 191 eb-buster is not running
lxc-destroy: eb-buster: tools/lxc_destroy.c: main: 259 Container is not defined
Setting up the GPG keyring
ERROR: Unable to fetch GPG key from keyserver
lxc-create: eb-buster: lxccontainer.c: create_run_template: 1617 Failed to create container from template
lxc-create: eb-buster: tools/lxc_create.c: main: 327 Failed to create container eb-buster

Something went wrong. The installation couldn't be completed!
`
Any clue ? Would you need anymore information ?

**Comment by filippo82** [comment]
Hi, have you followed the **exact** instructions [here](https://github.com/emrahcom/emrah-buster-templates/blob/master/doc/jitsi_cluster.md#51-my-kernel-has-no-support-for-the-snd_aloop-module-how-can-i-install-the-standard-linux-kernel)?

**Comment by emrahcom** [comment]
Hello @Guiraud,

 This seems a temporary DNS or network issue.

**Comment by emrahcom** [comment]
The installer uses now a more stable keyserver
